
window.WHISKYLOG_VERSION='2.38';
const APP_KEY='whiskylog_v234_state';
const LEGACY_KEYS=['whiskylog_v2_state','whiskylog_state_v2','whiskylog_state','whiskylog_stable_v133'];
let page='home', selectedStockStatus='', selectedTastingBottleId='', editTastingId='', editLibraryId='', editStockId='', ratingsBottleId='';
let settings={ownerName:'Kenneth',currency:'NOK',language:'no',defaultTastingMl:20};
let state=loadState();

function uid(){return 'id_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}
function readJson(k,f){try{const r=localStorage.getItem(k);return r?JSON.parse(r):f}catch(e){return f}}
function normalizeState(s){s=s||{};return{bases:Array.isArray(s.bases)?s.bases:(Array.isArray(s.library)?s.library:[]),bottles:Array.isArray(s.bottles)?s.bottles:(Array.isArray(s.stock)?s.stock:[]),tastings:Array.isArray(s.tastings)?s.tastings:[],comments:Array.isArray(s.comments)?s.comments:[],wishlist:Array.isArray(s.wishlist)?s.wishlist:[]}}
function loadState(){const cur=readJson(APP_KEY,null);if(cur)return normalizeState(cur);for(const k of LEGACY_KEYS){const v=readJson(k,null);if(v){const n=normalizeState(v.state||v.data||v);localStorage.setItem(APP_KEY,JSON.stringify(n));return n}}return{bases:[],bottles:[],tastings:[],comments:[],wishlist:[]}}
function save(){localStorage.setItem(APP_KEY,JSON.stringify(state))}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function num(v){const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:0}
function money(v){return num(v).toFixed(2)+' '+(settings.currency||'NOK')}
function clampScore(v){return Math.max(0,Math.min(100,num(v)))}
function tastingPercent(t){const vals=[t.visualScore,t.aromaScore,t.tasteScore,t.finishScore,t.overallScore].map(clampScore).filter(v=>v>0);if(vals.length)return Math.round(vals.reduce((a,b)=>a+b,0)/vals.length*10)/10;const l=num(t.average||t.score);if(l>0){if(l<=1)return Math.round(l*1000)/10;if(l<=10)return Math.round(l*100)/10;return Math.round(l*10)/10}return 0}
function fmtPct(v){const n=num(v);return n>0?n.toFixed(1)+' %':'0.0 %'}
function getBase(id){return state.bases.find(b=>b.id===id)}
function getBottle(id){return state.bottles.find(b=>b.id===id)}
function bottleBase(b){return b?state.bases.find(x=>x.id===b.libraryId||x.id===b.baseId||x.id===b.baseID)||b.base||null:null}
function img(base){const s=base&&(base.image||base.img||base.photo||base.picture);return s?`<img class="thumb" src="${s}" alt="">`:`<div class="thumb">🥃</div>`}
function bottleVolume(id){const b=getBottle(id);if(!b)return 0;const base=bottleBase(b)||{};const full=num(base.volume||b.volume||700);if(b.forceEmpty||b.status==='empty')return 0;const empty=num(base.emptyWeight||base.emptyWeightG||b.emptyWeight||b.emptyWeightG);const fullW=num(base.fullWeight||base.fullWeightG||b.fullWeight||b.fullWeightG);const cur=num(b.currentWeight||b.currentWeightG||b.weight||b.weightG);if(fullW>0&&empty>0&&cur>0&&fullW>empty){return Math.round(full*Math.max(0,Math.min(1,(cur-empty)/(fullW-empty))))}const tasted=state.tastings.filter(t=>t.bottleId===id).reduce((a,t)=>a+num(t.ml),0);return Math.max(0,Math.round(full-tasted))}
function valueLeft(id){const b=getBottle(id);if(!b)return 0;const base=bottleBase(b)||{};const p=num(b.price||base.price||b.purchasePrice||base.purchasePrice);const full=num(base.volume||b.volume||700);return full>0?p*bottleVolume(id)/full:0}
function bottleStatus(b){if(b.forceEmpty||b.status==='empty')return'empty';const vol=bottleVolume(b.id),base=bottleBase(b)||{},full=num(base.volume||b.volume||700);if(vol<=0)return'empty';if(vol>=full-1&&!state.tastings.some(t=>t.bottleId===b.id))return'unopened';return'opened'}
function dropsPerLiter(t){if(t.mode!=='water')return'';const d=num(t.drops),ml=num(t.ml);return d>0&&ml>0?Math.round(d/ml*1000)+' dråper/L':''}
function bottleAvgPct(id){const vals=state.tastings.filter(t=>t.bottleId===id).map(tastingPercent).filter(v=>v>0);return vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length*10)/10:0}
function bottleStatsPct(id){const vals=state.tastings.filter(t=>t.bottleId===id).map(tastingPercent).filter(v=>v>0);if(!vals.length)return{min:0,avg:0,max:0,count:0};return{min:Math.round(Math.min(...vals)*10)/10,avg:Math.round(vals.reduce((a,b)=>a+b,0)/vals.length*10)/10,max:Math.round(Math.max(...vals)*10)/10,count:vals.length}}
function averageScoreForLibrary(id){const bids=state.bottles.filter(b=>b.libraryId===id||b.baseId===id).map(b=>b.id),vals=state.tastings.filter(t=>bids.includes(t.bottleId)).map(tastingPercent).filter(v=>v>0);return vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length*10)/10:0}
function shell(c,a){document.getElementById('app').innerHTML=`<header><div class="kicker">PREMIUM BRENNEVINSJOURNAL</div><h1>Kenneth's WhiskyLog</h1><div class="version">WhiskyLog v${window.WHISKYLOG_VERSION}</div>${a&&a!=='home'?`<button class="ghost backBtn" data-action="home">← Tilbake</button>`:''}</header><main>${c}</main>`}
function card(t,s,a,i='🥃'){
  const tiles = a === 'stock'
    ? ['🥃','📦','🍷','🗄️']
    : a === 'logging'
      ? ['📝','⚖️','➕','📚']
      : a === 'overview'
        ? ['📊','🏆','💰','🕘']
        : ['⭐','🛒','📌','💡'];
  return `<section class="card menuCard oldMenuCard" data-action="${a}">
    <div class="menuLeft">
      <div class="menuIcon">${i}</div>
      <div>
        <h2>${t}</h2>
        <p class="sub">${s}</p>
      </div>
    </div>
    <div class="menuTiles">${tiles.map(x=>`<span>${x}</span>`).join('')}</div>
  </section>`;
}
function renderHome(){shell(`<section class="hero"><h2>Din personlige brennevinslogg</h2><p class="sub">Personlig loggføring av flasker, smakinger, beholdning og fremtidige kjøp.</p></section><section class="menuGrid">${card('Min beholdning','Uåpnede, åpnede og tomme flasker samlet på ett sted.','stock','🥃')}${card('Loggføring','Registrer smaking, korriger beholdning og legg til flasker.','logging','📝')}${card('Oversikt / statistikk','Rangering, score, verdi og historikk.','overview','📊')}${card('Ønskeliste','Fremtidige flasker og kjøpsideer.','wishlist','⭐')}</section><button class="ghost fullWidth" data-action="settings">⚙️ Innstillinger</button>`,'home')}
function renderStock(){const groups=[['unopened','Uåpnede flasker','📦'],['opened','Åpnede flasker','🍷'],['empty','Tomme flasker','🗄️']];shell(`<section class="hero"><h2>Min beholdning</h2><p class="sub">Uåpnede, åpnede og tomme flasker samlet på ett sted.</p></section><section class="grid">${groups.map(([st,title,ic])=>{const rows=state.bottles.filter(b=>bottleStatus(b)===st),val=rows.reduce((a,b)=>a+valueLeft(b.id),0),ml=rows.reduce((a,b)=>a+bottleVolume(b.id),0);return`<section class="card" data-action="stock-list" data-status="${st}"><div class="menuIcon">${ic}</div><h2>${title}</h2><p class="sub">${rows.length} flasker · ${money(val)}</p><p class="sub">${Math.round(ml)} ml</p><div class="miniImages">${rows.slice(0,4).map(b=>img(bottleBase(b)||{})).join('')}</div></section>`}).join('')}</section><section class="buttonRow"><button class="ghost" data-action="add-stock">Kjøpt flaske</button><button class="ghost" data-action="tasting">Registrer smaking</button><button class="ghost" data-action="logging">Korriger beholdning</button></section>`,'stock')}
function renderStockList(){const title=selectedStockStatus==='unopened'?'Uåpnede flasker':selectedStockStatus==='opened'?'Åpnede flasker':'Tomme flasker',rows=state.bottles.filter(b=>bottleStatus(b)===selectedStockStatus);shell(`<section class="hero"><h2>${title}</h2></section><section class="card"><div class="list">${rows.length?rows.map(b=>{const base=bottleBase(b)||{};return`<div class="item">${img(base)}<div><div class="title">${esc(base.name||b.name||'Ukjent')}</div><div class="meta">${esc(base.type||'')} · ${bottleVolume(b.id)} ml igjen · ${money(valueLeft(b.id))}</div><div class="small">Kjøpt: ${esc(b.purchaseDate||b.date||'')}</div></div><div class="actions"><button class="ghost" data-action="edit-stock" data-id="${b.id}">Rediger</button>${selectedStockStatus==='opened'?`<button class="ghost" data-action="tasting-bottle" data-id="${b.id}">Registrer smaking</button>`:''}<button class="danger" data-action="delete-stock" data-id="${b.id}">Slett</button></div></div>`}).join(''):`<p class="sub">Ingen registreringer ennå.</p>`}</div></section>`,'stockList')}
function renderOverview(){const totalValue=state.bottles.reduce((a,b)=>a+valueLeft(b.id),0),totalMl=state.bottles.reduce((a,b)=>a+bottleVolume(b.id),0),ranked=state.bases.map(base=>({base,score:averageScoreForLibrary(base.id)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);shell(`<section class="hero"><h2>Oversikt / statistikk</h2><p class="sub">Rangering, score, verdi og historikk.</p></section><section class="grid"><section class="card stat"><h2>${money(totalValue)}</h2><p class="sub">verdi</p></section><section class="card stat"><h2>${Math.round(totalMl)} ml</h2><p class="sub">volum i beholdning</p></section><section class="card stat"><h2>${state.tastings.length}</h2><p class="sub">registrerte smakinger</p></section></section><section class="card ratingsMenuCard"><h2>Vurderinger</h2><p class="sub">Alle flaskescore med bilde, søk og detaljvisning.</p><button class="primary fullWidth" data-action="ratings">Åpne vurderinger</button></section><section class="card"><h2>Flaskerangering</h2><div class="list">${ranked.length?ranked.map(x=>`<div class="item" data-action="ratings">${img(x.base)}<div><div class="title">${esc(x.base.name||'')}</div><div class="meta"><b>${fmtPct(x.score)}</b></div></div></div>`).join(''):`<p class="sub">Ingen registreringer ennå.</p>`}</div></section>`,'overview')}
function renderRatings(){const q=(window.__ratingsSearch||'').toLowerCase();let bottles=state.bottles.map(b=>({b,base:bottleBase(b),avg:bottleAvgPct(b.id),count:state.tastings.filter(t=>t.bottleId===b.id).length})).filter(x=>x.base&&x.count>0);if(q)bottles=bottles.filter(x=>String(x.base.name||'').toLowerCase().includes(q));bottles.sort((a,b)=>b.avg-a.avg);shell(`<section class="hero"><h2>Vurderinger</h2><p class="sub">Flaskescore sortert med høyeste score øverst.</p></section><section class="card"><label>Søk etter flaske</label><input id="ratingsSearch" placeholder="Søk etter flaske" value="${esc(window.__ratingsSearch||'')}"></section><section class="card"><div class="list">${bottles.length?bottles.map(x=>`<div class="item ratingsItem" data-action="rating-detail" data-id="${x.b.id}">${img(x.base)}<div><div class="title">${esc(x.base.name||'')}</div><div class="meta"><b>${fmtPct(x.avg)}</b></div><div class="small">Antall smakinger: ${x.count}</div></div><div class="actions"><button class="ghost" data-action="rating-detail" data-id="${x.b.id}">Åpne</button></div></div>`).join(''):`<p class="sub">Ingen vurderinger ennå.</p>`}</div></section>`,'ratings');document.getElementById('ratingsSearch')?.addEventListener('input',e=>{window.__ratingsSearch=e.target.value;renderRatings()})}
function scoreLine(l,s,n){return`<div class="scoreLineOne"><span class="scoreName">${l}</span><span class="scorePoints">${esc(s||'-')} poeng</span><span class="scoreNote">${esc(n||'')}</span></div>`}
function tastingDetailItem(t){const w=dropsPerLiter(t);return`<div class="item tastingDetailItem"><div><div class="title">${esc(t.date||'')} · ${t.mode==='water'?'Med vann':'Neat'} ${w?'· '+w:''}</div><div class="meta">Totalvurdering: <b>${fmtPct(tastingPercent(t))}</b> · ${esc(t.ml||'')} ml</div><div class="scoreGrid">${scoreLine('Visuelt',t.visualScore,t.visualNote)}${scoreLine('Lukt',t.aromaScore,t.aromaNote)}${scoreLine('Smak',t.tasteScore,t.tasteNote)}${scoreLine('Ettersmak',t.finishScore,t.finishNote)}${scoreLine('Helhetsinntrykk',t.overallScore,t.overallNote)}</div>${t.notes?`<p class="small">${esc(t.notes)}</p>`:''}</div><div class="actions"><button class="ghost" data-action="edit-tasting" data-id="${t.id}">Rediger</button><button class="danger" data-action="delete-tasting" data-id="${t.id}">Slett</button></div></div>`}
function renderRatingDetail(){const b=getBottle(ratingsBottleId),base=bottleBase(b),st=bottleStatsPct(ratingsBottleId),rows=state.tastings.filter(t=>t.bottleId===ratingsBottleId).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));shell(`<section class="hero">${img(base||{})}<h2>${esc(base?.name||'Ukjent')}</h2><p class="sub">Laveste: ${fmtPct(st.min)} · Snitt: ${fmtPct(st.avg)} · Høyeste: ${fmtPct(st.max)}</p></section><section class="card"><h2>Smakinger</h2><p class="sub">Nyeste øverst.</p><div class="list">${rows.length?rows.map(tastingDetailItem).join(''):`<p class="sub">Ingen smakinger ennå.</p>`}</div></section>`,'ratingDetail')}
function renderLogging(){shell(`<section class="hero"><h2>Loggføring</h2><p class="sub">Registrer smaking, korriger beholdning og legg til flasker.</p></section><section class="menuGrid">${card('Flaskebibliotek','Registrer og rediger grunnflasker.','library','📚')}${card('Kjøpt flaske','Legg inn kjøp og beholdning.','add-stock','📦')}${card('Registrer smaking','Score, volum og smaksnotater.','tasting','🥃')}${card('Korriger beholdning','Oppdater vekt/reststatus.','stock','⚖️')}</section>`,'logging')}
function renderLibrary(){const form=libraryForm();shell(`<section class="hero"><h2>Flaskebibliotek</h2><p class="sub">Grunndata kan redigeres her.</p></section><section class="card">${form}</section><section class="card"><h2>Bibliotek</h2><div class="list">${state.bases.length?state.bases.map(base=>`<div class="item">${img(base)}<div><div class="title">${esc(base.name||'')}</div><div class="meta">${esc(base.type||'')} · ${esc(base.abv||'')}% · ${esc(base.volume||'')} ml</div></div><div class="actions"><button class="ghost" data-action="edit-library" data-id="${base.id}">Rediger</button><button class="danger" data-action="delete-library" data-id="${base.id}">Slett</button></div></div>`).join(''):`<p class="sub">Ingen registreringer ennå.</p>`}</div></section>`,'library')}
function libraryForm(){const b=editLibraryId?getBase(editLibraryId)||{}:{};return`<form id="libraryForm"><label>Navn</label><input name="name" value="${esc(b.name||'')}"><label>Destilleri / produsent</label><input name="distillery" value="${esc(b.distillery||'')}"><label>Type</label><input name="type" value="${esc(b.type||'Whisky')}"><label>Alkohol %</label><input name="abv" type="number" step="0.1" value="${esc(b.abv||'')}"><label>Flaskevolum ml</label><input name="volume" type="number" value="${esc(b.volume||700)}"><label>Vekt full flaske g</label><input name="fullWeight" type="number" value="${esc(b.fullWeight||'')}"><label>Vekt tom flaske g</label><input name="emptyWeight" type="number" value="${esc(b.emptyWeight||'')}"><label>Region / land</label><input name="region" value="${esc(b.region||'')}"><label>Bilde</label><input name="imageFile" type="file" accept="image/*"><label>Bibliotekkommentar</label><textarea name="comment">${esc(b.comment||'')}</textarea><button class="primary" type="submit">${editLibraryId?'Lagre endring':'Lagre i bibliotek'}</button></form>`}
async function fileToDataUrl(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
async function saveLibraryForm(form){const fd=new FormData(form),cur=editLibraryId?getBase(editLibraryId)||{}:{};let imgv=cur.image;if(fd.get('imageFile')&&fd.get('imageFile').size)imgv=await fileToDataUrl(fd.get('imageFile'));const item={id:editLibraryId||uid(),name:fd.get('name'),distillery:fd.get('distillery'),type:fd.get('type'),abv:num(fd.get('abv')),volume:num(fd.get('volume'))||700,fullWeight:num(fd.get('fullWeight')),emptyWeight:num(fd.get('emptyWeight')),region:fd.get('region'),image:imgv,comment:fd.get('comment')};if(editLibraryId)state.bases=state.bases.map(x=>x.id===editLibraryId?item:x);else state.bases.push(item);editLibraryId='';save();renderLibrary()}
function renderAddStock(){
const editing=editStockId?getBottle(editStockId):null;
const current=editing||{};
shell(`<section class="hero"><h2>${editing?'Rediger flaske':'Kjøpt flaske'}</h2><p class="sub">${editing?'Endre kjøpsdata, pris og nåværende vekt.':'Legg inn kjøp og beholdning.'}</p></section><section class="card"><form id="stockForm"><label>Flaske</label><select name="libraryId">${state.bases.map(b=>`<option value="${b.id}" ${(current.libraryId===b.id||current.baseId===b.id)?'selected':''}>${esc(b.name)}</option>`).join('')}</select><label>Kjøpsdato</label><input name="purchaseDate" type="date" value="${esc(current.purchaseDate||current.date||new Date().toISOString().slice(0,10))}"><label>Pris</label><input name="price" type="number" step="0.01" value="${esc(current.price||current.purchasePrice||'')}"><label>Nåværende vekt g</label><input name="currentWeight" type="number" value="${esc(current.currentWeight||current.currentWeightG||current.weight||current.weightG||'')}"><label>Status</label><select name="status"><option value="" ${!current.status?'selected':''}>Automatisk</option><option value="unopened" ${current.status==='unopened'?'selected':''}>Uåpnet</option><option value="opened" ${current.status==='opened'?'selected':''}>Åpnet</option><option value="empty" ${current.status==='empty'?'selected':''}>Tom</option></select><button class="primary" type="submit">${editing?'Lagre endring':'Lagre kjøpt flaske'}</button></form></section>`,'addStock')}

function scoreInputs(label,key,t){return`<label>${label} poeng 0–100</label><input name="${key}Score" type="number" min="0" max="100" value="${esc(t[key+'Score']||'')}"><label>${label} kort notat</label><input name="${key}Note" maxlength="60" value="${esc(t[key+'Note']||'')}">`}
function renderTasting(){const t=editTastingId?state.tastings.find(x=>x.id===editTastingId)||{}:{},opts=state.bottles.filter(b=>bottleStatus(b)!=='empty').map(b=>{const base=bottleBase(b)||{},sel=(t.bottleId||selectedTastingBottleId)===b.id?'selected':'';return`<option value="${b.id}" ${sel}>${esc(base.name||'Ukjent')}</option>`}).join('');shell(`<section class="hero"><h2>${editTastingId?'Rediger smaking':'Registrer smaking'}</h2><p class="sub">Score, volum og smaksnotater.</p></section><section class="card"><form id="tastingForm"><label>Flaske</label><select name="bottleId">${opts}</select><label>Smaksdato</label><input name="date" type="date" value="${esc(t.date||new Date().toISOString().slice(0,10))}"><label>Smakstype</label><select name="mode"><option value="neat" ${t.mode!=='water'?'selected':''}>Neat</option><option value="water" ${t.mode==='water'?'selected':''}>Med vann</option></select><label>Antall dråper vann</label><input name="drops" type="number" value="${esc(t.drops||'')}"><label>Mengde ml</label><input name="ml" type="number" value="${esc(t.ml||settings.defaultTastingMl)}">${scoreInputs('Visuelt','visual',t)}${scoreInputs('Lukt','aroma',t)}${scoreInputs('Smak','taste',t)}${scoreInputs('Ettersmak','finish',t)}${scoreInputs('Helhetsinntrykk','overall',t)}<label>Notater</label><textarea name="notes">${esc(t.notes||'')}</textarea><div class="buttonRow"><button class="primary" type="submit">${editTastingId?'Lagre endring':'Lagre'}</button><button class="danger" type="button" data-action="last-sip-form">Siste sipp smakt</button></div></form></section>`,'tasting')}
function saveTastingForm(form){const fd=new FormData(form);const item={id:editTastingId||uid(),bottleId:fd.get('bottleId'),date:fd.get('date'),mode:fd.get('mode'),drops:num(fd.get('drops')),ml:num(fd.get('ml')),visualScore:num(fd.get('visualScore')),visualNote:fd.get('visualNote'),aromaScore:num(fd.get('aromaScore')),aromaNote:fd.get('aromaNote'),tasteScore:num(fd.get('tasteScore')),tasteNote:fd.get('tasteNote'),finishScore:num(fd.get('finishScore')),finishNote:fd.get('finishNote'),overallScore:num(fd.get('overallScore')),overallNote:fd.get('overallNote'),notes:fd.get('notes')};if(editTastingId)state.tastings=state.tastings.map(x=>x.id===editTastingId?item:x);else state.tastings.push(item);editTastingId='';selectedTastingBottleId='';save();page='ratings';render()}
function renderWishlist(){
const total=(state.wishlist||[]).reduce((a,w)=>a+num(w.price),0);
shell(`<section class="hero"><h2>Ønskeliste</h2><p class="sub">Fremtidige flasker og kjøpsideer.</p></section>
<section class="grid"><section class="card stat"><h2>${(state.wishlist||[]).length}</h2><p class="sub">flasker</p></section><section class="card stat"><h2>${money(total)}</h2><p class="sub">total pris</p></section></section>
<section class="card"><h2>Legg til ønskeflaske</h2><form id="wishlistForm"><label>Navn</label><input name="name"><label>Type</label><input name="type" placeholder="Whisky, bourbon, rom ..."><label>Pris</label><input name="price" type="number" step="0.01"><label>Butikk / lenke</label><input name="link"><label>Bilde</label><input name="imageFile" type="file" accept="image/*"><label>Kommentar</label><textarea name="comment"></textarea><button class="primary" type="submit">Lagre ønskeflaske</button></form></section>
<section class="card"><h2>Ønskeliste</h2><div class="list">${(state.wishlist||[]).length?(state.wishlist||[]).map(w=>`<div class="item">${w.image?`<img class="thumb" src="${w.image}" alt="">`:`<div class="thumb">⭐</div>`}<div><div class="title">${esc(w.name||'')}</div><div class="meta">${esc(w.type||'')} · ${money(w.price||0)}</div>${w.link?`<div class="small">${esc(w.link)}</div>`:''}${w.comment?`<div class="small">${esc(w.comment)}</div>`:''}</div><div class="actions"><button class="danger" data-action="delete-wishlist" data-id="${w.id}">Slett</button></div></div>`).join(''):`<p class="sub">Ingen flasker på ønskelisten ennå.</p>`}</div></section>`,'wishlist')}
function renderSettings(){shell(`<section class="hero"><h2>Innstillinger</h2></section><section class="card"><label>Navn</label><input id="settingName" value="${esc(settings.ownerName)}"><label>Valuta</label><input id="settingCurrency" value="${esc(settings.currency)}"><label>Standard smaksvolum ml</label><input id="settingMl" type="number" value="${esc(settings.defaultTastingMl)}"><button class="primary" data-action="save-settings">Lagre innstillinger</button></section><section class="card"><h2>Backup</h2><p class="sub">Backup inkluderer bibliotek, flasker, bilder, smakinger, kommentarer, ønskeliste og innstillinger.</p><div class="buttonRow"><button class="primary" data-action="backup">Lagre backup til fil</button><button class="ghost" data-action="restore">Hent backup fra fil</button></div></section>`,'settings')}
function render(){if(page==='home')return renderHome();if(page==='stock')return renderStock();if(page==='stockList')return renderStockList();if(page==='overview')return renderOverview();if(page==='ratings')return renderRatings();if(page==='ratingDetail')return renderRatingDetail();if(page==='logging')return renderLogging();if(page==='library')return renderLibrary();if(page==='addStock')return renderAddStock();if(page==='tasting')return renderTasting();if(page==='wishlist')return renderWishlist();if(page==='settings')return renderSettings();renderHome()}
function exportBackup(){const json=JSON.stringify({app:'WhiskyLog',backupVersion:window.WHISKYLOG_VERSION,schemaVersion:2,createdAt:new Date().toISOString(),state,settings},null,2),fn=`WhiskyLog_backup_v${window.WHISKYLOG_VERSION}_${new Date().toISOString().slice(0,19).replace(/[:T]/g,'-')}.json`;const file=new File([json],fn,{type:'application/json'});if(navigator.canShare&&navigator.canShare({files:[file]})&&navigator.share){navigator.share({files:[file],title:'WhiskyLog backup'});return}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([json],{type:'application/json'}));a.download=fn;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importBackup(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json,text/plain,*/*';input.onchange=async()=>{const f=input.files&&input.files[0];if(!f)return;try{let txt=(await f.text()).replace(/^\uFEFF/,'').trim();const first=txt.indexOf('{'),last=txt.lastIndexOf('}');if(first>=0&&last>first)txt=txt.slice(first,last+1);const p=JSON.parse(txt);state=normalizeState(p.state||p.data||p);if(p.settings)settings=Object.assign(settings,p.settings);save();alert('Backup importert.');page='home';render()}catch(e){alert('Kunne ikke hente backup: '+e.message)}};input.click()}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action,id=el.dataset.id;if(['home','stock','overview','ratings','logging','library','add-stock','tasting','wishlist','settings'].includes(a)){if(a==='add-stock')editStockId='';if(a==='library')editLibraryId='';page=a==='add-stock'?'addStock':a;render();return}if(a==='stock-list'){selectedStockStatus=el.dataset.status;page='stockList';render();return}if(a==='rating-detail'){ratingsBottleId=id;page='ratingDetail';render();return}if(a==='tasting-bottle'){selectedTastingBottleId=id;page='tasting';render();return}if(a==='edit-tasting'){editTastingId=id;page='tasting';render();return}if(a==='delete-tasting'){if(confirm('Slette denne smakingen?')){state.tastings=state.tastings.filter(t=>t.id!==id);save();render()}return}if(a==='edit-library'){editLibraryId=id;page='library';render();return}if(a==='delete-library'){if(confirm('Slette denne bibliotekflasken?')){state.bases=state.bases.filter(b=>b.id!==id);save();render()}return}if(a==='edit-stock'){editStockId=id;page='addStock';render();return}if(a==='delete-stock'){if(confirm('Slette denne flasken fra beholdningen?')){state.bottles=state.bottles.filter(b=>b.id!==id);save();render()}return}if(a==='last-sip-form'){const form=document.getElementById('tastingForm');const bottleId=form?new FormData(form).get('bottleId'):selectedTastingBottleId;if(!bottleId){alert('Velg flaske først.');return}if(confirm('Flytte flasken til tomme flasker?')){state.bottles=state.bottles.map(b=>b.id===bottleId?Object.assign({},b,{status:'empty',forceEmpty:true,currentWeight:0}):b);save();page='stock';render()}return}
if(a==='delete-wishlist'){if(confirm('Slette denne ønskeflasken?')){state.wishlist=(state.wishlist||[]).filter(w=>w.id!==id);save();render()}return}
if(a==='backup'){exportBackup();return}if(a==='restore'){importBackup();return}if(a==='save-settings'){settings.ownerName=document.getElementById('settingName').value;settings.currency=document.getElementById('settingCurrency').value||'NOK';settings.defaultTastingMl=num(document.getElementById('settingMl').value)||20;alert('Innstillinger lagret.');return}})
document.addEventListener('submit',async e=>{if(e.target.id==='libraryForm'){e.preventDefault();await saveLibraryForm(e.target)}if(e.target.id==='stockForm'){e.preventDefault();const fd=new FormData(e.target);const item={id:editStockId||uid(),libraryId:fd.get('libraryId'),purchaseDate:fd.get('purchaseDate'),price:num(fd.get('price')),currentWeight:num(fd.get('currentWeight')),status:fd.get('status')||''};if(editStockId){state.bottles=state.bottles.map(b=>b.id===editStockId?Object.assign({},b,item):b);editStockId=''}else{state.bottles.push(item)}save();page='stock';render()}if(e.target.id==='tastingForm'){e.preventDefault();saveTastingForm(e.target)}
if(e.target.id==='wishlistForm'){e.preventDefault();const fd=new FormData(e.target);let image='';if(fd.get('imageFile')&&fd.get('imageFile').size)image=await fileToDataUrl(fd.get('imageFile'));state.wishlist=state.wishlist||[];state.wishlist.push({id:uid(),name:fd.get('name'),type:fd.get('type'),price:num(fd.get('price')),link:fd.get('link'),comment:fd.get('comment'),image});save();renderWishlist();}})
document.addEventListener('DOMContentLoaded',render);



/* v2.38 library edit repair */
window.__wlLibraryEditRepair238 = true;

function saveLibraryFormFixed238(form){
  const fd = new FormData(form);
  const current = editLibraryId ? getBase(editLibraryId) || {} : {};
  const finish = (image) => {
    const item = {
      id: editLibraryId || uid(),
      name: fd.get('name'),
      distillery: fd.get('distillery'),
      type: fd.get('type'),
      abv: num(fd.get('abv')),
      volume: num(fd.get('volume')) || 700,
      fullWeight: num(fd.get('fullWeight')),
      emptyWeight: num(fd.get('emptyWeight')),
      region: fd.get('region'),
      image: image || current.image || '',
      comment: fd.get('comment')
    };
    if(editLibraryId){
      state.bases = state.bases.map(x => x.id === editLibraryId ? Object.assign({}, x, item) : x);
      editLibraryId = '';
    }else{
      state.bases.push(item);
    }
    save();
    renderLibrary();
  };
  const file = fd.get('imageFile');
  if(file && file.size){
    fileToDataUrl(file).then(finish);
  }else{
    finish(current.image || '');
  }
}

const oldSaveLibraryForm238 = typeof saveLibraryForm === 'function' ? saveLibraryForm : null;
saveLibraryForm = saveLibraryFormFixed238;

document.addEventListener('click', function(e){
  const el = e.target.closest('[data-action="edit-library"]');
  if(!el) return;
  e.preventDefault();
  e.stopPropagation();
  editLibraryId = el.dataset.id;
  page = 'library';
  render();
}, true);

